## 2. 데이터 유형
- Scalar : 숫자 하나만으로 이루어진 데이터
- Vector : 여러 숫자가 특정한 순서대로 모여 있는 n행 1열 데이터 
- Matrix : 복수의 차원을 가지는 데이터 레코드가 다시 여러 개 있는 경우의 데이터를 표기
- tensor : 같은 크기의 행렬이 여러 개 같이 묶여 있는 것

### 전치 연산
- 행과 열을 바꾸는 연산
    - 속성 T를 이용

In [8]:
# transpose : 연습문제 2.1.3
X = np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2]])
X.T
# 1차원 ndarray는 전치 연산이 정의 되지 않는 점을 주의한다.

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [9]:
(X.T).T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

### 특수한 벡터와 행렬
- 영벡터 : 모든 원소가 0인 N차원 벡터
- 일벡터 : 모든 원소가 1인 N차원 벡터
- 정방행렬 : 행 개수와 열 개수가 같은 행렬
- 대각행렬 : 비대각 요소가 0인 행렬(비대각성분만 0이기만 하면되고 대각성분은 0이든 아니든 상관없다. 또 반드시 정방행렬일 필요는 없다.)
- 항등행렬 : 대각행렬 중에서도 모든 대각성분의 값이 1인 대각행렬 I
    - 어떤 행렬이든 항등행렬을 곱하면 그 행렬의 값이 변하지 않는다.
- 대칭행렬 : 전치연산을 통해 얻은 전치행렬과 원래의 행렬이 같은 행렬 (정방행렬만 대칭행렬이 될 수 있다.)

In [10]:
# 연습문제 2.1.4
# 영벡터
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# 일벡터
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [12]:
# 대각행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
# 항등행렬
np.identity(5) # np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 2.2 벡터와 행렬의 연산
- 덧셈과 뺄셈 : 같은 크기를 가진 두 개의 벡터나 행렬은 같은 위치에 있는 원소끼리 덧셈과 뺄셈을 한다. (요소별 연산)
- 곱셈
    - 행렬,벡터와 스칼라 곱 => 브로드 캐스팅
    - 벡터와 벡터의 곱 => 내적
        - 두 벡터의 차원(길이)이 같아야한다.
        - 앞의 벡터가 행벡터이고 뒤의 벡터가 열벡터
        - 내적의 결과값은 스칼라
        

### 내적의 활용 1 : 가중합
- 가중합은 데이터를 단순히 합하는 것이 아니라 각각의 수에 어떤 가중치를 곱한 후 이 곱셈 결과들을 다시 합한 것

In [18]:

# 연습문제 2.2.1
p = np.array([[100],[80],[50]])
n = np.array([[3],[4],[5]])

(p.T@n)[0][0]

870

### 내적의 활용 2 : 가중평균
- 가중합의 가중치값을 전체 가중치값의 합으로 나눈 값이 가중평균

In [22]:

X.mean()

2.4625

### 내적의 활용 3 : 유사도
- 유사도는 두 벡터가 갊은 정도를 정량적으로 나타낸 값. (두 벡터가 비슷한 경우 유사도가 커지고 반대의 경유 유사도가 작아진다.)
     - 코사인 유사도

In [23]:
# 연습문제 2.2.3
from sklearn.datasets import load_digits
X = load_digits().data

In [27]:
X[0]@X[9]

2807.0

In [28]:
X@X.T

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

### 내적의 활용 4 : 선형회귀 모형
- 독립변수 x 에서 종속변수 y를 예측하는 방법의 하나
    - 독립변수 x 벡터와 가중치 w 벡터와의 가중합으로 계산

### 내적의 활용 5 : 제곱합
- 데이터를 제곱한 뒤 이 값을 모두 더한 값이 제곱합
- ```X.T@X```

### 행렬과 행렬의 곱셈
- C = AB -> Cij = ai.T@bj
- 행렬 A의 열의 수가 뒤의 행렬 B의 행의 수와 일치해야만 한다.

In [36]:
# 연습문제 2.2.4
A = np.array([1,2,3])
B = np.array([[4,7],[5,8],[6,9]])
np.dot(A,B)

array([32, 50])

In [38]:
C = np.array([[1,2],[3,4]])
D = np.array([[5,6],[7,8]])
np.dot(C,D)

array([[19, 22],
       [43, 50]])

In [39]:
np.dot(D,C)

array([[23, 34],
       [31, 46]])

In [40]:
E = np.array([[1,2],[3,4],[5,6]])
E@E.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [41]:
E.T@E

array([[35, 44],
       [44, 56]])

### 행렬과 벡터의 곱
- 행렬 x 벡터 = 벡터

## 행렬 크기의 정의
- 놈
    - 놈은 항상 0보다 크거나 같다.
    - 제곱합은 놈의 제곱이다.
- 대각합
    - 정방행렬에 대해서만 정의가 되며, 정방행렬의 대각성분을 다 더하면 된다.
    - 음수가 나올 수 있다.(크기는 아니고 크기와 비슷한 개념이다.)
    - tr(AB) = tr(BA)
- 행렬식
    - 재귀적인 방법으로 정의된다.
    - 행렬식이 0이면 역행렬이 존재하지 않는다.
    

In [10]:
# norm
A = (np.arange(9)-4).reshape((3,3))
np.linalg.norm(A)

7.745966692414834

In [11]:
# trace
np.trace(np.eye(3))

3.0

In [12]:
# determinant
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

0.0

### 역행렬
- 전치행렬의 역행렬은 역행렬의 전치행렬과 같다. 따라서 대칭행렬의 역행렬도 대칭행렬이다.
- 두 개 이상의 정방행렬의 곱은 같은 크기의 정방행렬이 된다.(역행렬 분배법칙시 전치행렬 처름 순서가 바뀜)



In [1]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

### 미지수 수와 방정식 수
- 1. 방정식 수가 미지수 수와 같다. (N=M)
- 2. 방정식 수가 미지수 수보다 적다. (N<M)
- 3. 방정식 수가 미지수 수보다 많다. (N>M)


### 3번의 경우 최소자승문제로 해결
- 좌변과 우변의 차이를 최소화하는 문제
    - 잔차를 최소화 하는 문제 (벡터의 놈을 최소화 하는 문제; 잔차=벡터)
    - 의사역행렬을 이용 p.133
   

In [2]:
A = np.array([[1,1,0],[0,1,1,],[1,1,1,],[1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [3]:
b = np.array([[2],[2],[3],[4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [5]:
# 의사역행렬
Apinv = np.linalg.inv(A.T@A)@A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [6]:
x = Apinv@b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [7]:
A@x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [10]:
# lstsq() 와 비교
x, resid, rank, s = np.linalg.lstsq(A,b)
x

<ipython-input-10-efdd8c49ab66>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A,b)


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [12]:
# 잔차 비교
resid, np.linalg.norm(A@x-b)**2

(array([0.00166667]), 0.001666666666666655)

In [16]:
# 2.4.6 연습문제

from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [19]:
# 최소자승문제로 가중치인(미지수) x를 구해 각 변수의 특징을 직관적으로 살펴볼 수  있다.
x, resid, rank, s = np.linalg.lstsq(X,y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


<ipython-input-19-0e4deaac89f9>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(X,y)
