In [8]:
x = np.array([[1,2,3],[1,2,3],[1,2,3]])
y = np.array([1,1,1])
1/9*(x.T)@y

array([0.33333333, 0.66666667, 1.        ])

In [11]:
a = np.array([1,2,3,4,5])
a@a

55

## 1. 보스턴 집값 예측

### 1.1 연립방정식 계산
- 연립방적식을 풀어서 가중치를 계산한다.
    - 역행렬을 이용해 연립방정식을 풀 수 있다.


In [13]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4,[0,4,5,6]] # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [19]:
A # 특징 변수값들

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [20]:
b # 집값의 평균

array([24. , 21.6, 34.7, 33.4])

In [21]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


### 가중치 부호로부터 다음 사실을 알 수 있다. 집값은
- 범죄율(CRIM)에 반비례한다.
- 공기 오염도(NOX)에 반비례한다.
- 방의 개수(RM)에 비례한다.
- 오래된 정도 (AGE)에 반비례한다.

### 1.2 최소자승문제
- 방정식의 수가 미지수의 수보다 많을 때
    - lstsq()

In [25]:
x, resid, rank, s = np.linalg.lstsq(X,y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


/Users/sangjulee1/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.
