### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터는 빠르게 계산 해야 한다.
- 행렬 데이터를 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 백터, 매트릭스
        

In [1]:
import numpy as np

In [6]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능 (리스트에서는 여라가지 가능 했었음)
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [5]:
array2 = np.array(
    [[1,2,3],
    [4,5,6]]
)
array2.ndim, array2.shape # shape 바깥쪽에서 안쪽 차원을 써준다. 

(2, (2, 3))

In [11]:
# 행렬의 모양(shape) 변경하기
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# 행렬 데이터의 선택: offset index: masking

In [17]:
array2[1][::-1]

array([6, 5, 4])

In [20]:
array2[1,2] # == array2[1][2]

6

In [21]:
# 데이터 수정

In [23]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [24]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [28]:
# 브로드 캐스팅
array2[0] =0

In [29]:
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [31]:
array2[0] = [7,8,9]

In [40]:
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [38]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [41]:
# 조건을 줘서 필터링을 해주는 것이임 : True인것만 남기고 False제거
array2[idx] 

array([ 8,  9, 10])

In [42]:
array2[idx]  = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [43]:
# 행렬 데이터의 생성 2


In [45]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
data.dtype

dtype('float64')

In [48]:
data2= data.astype("int")
data2.dtype

dtype('int64')

In [49]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(5,10,2)

array([5, 7, 9])