### Summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성1 : ndarray 타입을 np.array(iterable) 형태로 생성
- 행렬의 생성2 : ones, zeros
- 행렬의 데이터 선택: array[x, y, z] 바깥쪽부터 안쪽으로
- 행렬 데이터 수정
    - 행렬 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arange: list에서 사용하는 range: 결과가 ndarray

### quiz 
- 100 ~ 130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 

```
datas = np.random.randint(100,130,size=(8*8))

```

- 데이터 타입이 정수 -> 문자열: ndarray.astype()

In [3]:
import numpy as np

In [6]:
datas = np.random.randint(100,130,size=(8,8))
datas

array([[128, 123, 105, 129, 127, 114, 102, 113],
       [102, 102, 113, 126, 107, 111, 113, 125],
       [124, 105, 106, 110, 118, 107, 111, 112],
       [124, 113, 117, 113, 121, 101, 111, 104],
       [113, 111, 111, 108, 117, 119, 125, 115],
       [109, 125, 126, 117, 101, 128, 111, 123],
       [128, 123, 113, 117, 125, 104, 125, 128],
       [102, 116, 101, 122, 121, 108, 122, 109]])

In [10]:
datas.astype(int)

array([[128, 123, 105, 129, 127, 114, 102, 113],
       [102, 102, 113, 126, 107, 111, 113, 125],
       [124, 105, 106, 110, 118, 107, 111, 112],
       [124, 113, 117, 113, 121, 101, 111, 104],
       [113, 111, 111, 108, 117, 119, 125, 115],
       [109, 125, 126, 117, 101, 128, 111, 123],
       [128, 123, 113, 117, 125, 104, 125, 128],
       [102, 116, 101, 122, 121, 108, 122, 109]])

In [24]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0


In [26]:
datas.dtype

dtype('int64')

In [27]:
result = datas.astype("str")
result

array([['128', '123', '105', '129', '127', '114', '102', '113'],
       ['102', '102', '113', '126', '107', '111', '113', '125'],
       ['124', '105', '106', '110', '118', '107', '111', '112'],
       ['124', '113', '117', '113', '121', '101', '111', '104'],
       ['113', '111', '111', '108', '117', '119', '125', '115'],
       ['109', '125', '126', '117', '101', '128', '111', '123'],
       ['128', '123', '113', '117', '125', '104', '125', '128'],
       ['102', '116', '101', '122', '121', '108', '122', '109']],
      dtype='<U21')

In [32]:
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"

In [33]:
result

array([['128', 'fiz', 'fbz', 'fiz', '127', 'fiz', 'fiz', '113'],
       ['fiz', 'fiz', '113', 'fiz', '107', 'fiz', '113', 'buz'],
       ['124', 'fbz', '106', 'buz', '118', '107', 'fiz', '112'],
       ['124', '113', 'fiz', '113', '121', '101', 'fiz', '104'],
       ['113', 'fiz', 'fiz', 'fiz', 'fiz', '119', 'buz', 'buz'],
       ['109', 'buz', 'fiz', 'fiz', '101', '128', 'fiz', 'fiz'],
       ['128', 'fiz', '113', 'fiz', 'buz', '104', 'buz', '128'],
       ['fiz', '116', '101', '122', '121', 'fiz', '122', '109']],
      dtype='<U21')

### Quiz
- 1 ~ 20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수



In [34]:
# np.min(ndarray), np.max(nparray)

datas = np.random.randint(1, 20, (5,5))
datas

array([[ 2,  7,  1, 11, 12],
       [ 6,  6,  2,  4, 14],
       [12, 16, 11,  2, 18],
       [ 1, 14, 19,  1, 15],
       [ 3,  8,  7, 10,  2]])

In [43]:
min_num = np.min(datas)
max_num = np.max(datas)

In [46]:
idx_min = datas==min_num
idx_max = datas==max_num

In [47]:
idx_min, idx_max

(array([[False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True, False, False,  True, False],
        [False, False, False, False, False]]),
 array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False]]))

In [48]:
result = datas.astype("str")

In [49]:
result

array([['2', '7', '1', '11', '12'],
       ['6', '6', '2', '4', '14'],
       ['12', '16', '11', '2', '18'],
       ['1', '14', '19', '1', '15'],
       ['3', '8', '7', '10', '2']], dtype='<U21')

In [50]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"


In [51]:
result

array([['2', '7', 'MIN', '11', '12'],
       ['6', '6', '2', '4', '14'],
       ['12', '16', '11', '2', '18'],
       ['MIN', '14', 'MAX', 'MIN', '15'],
       ['3', '8', '7', '10', '2']], dtype='<U21')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력


In [53]:
#linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [55]:
# logspace
# log10(x1) = 2, log10(x2) = 3, log10(x3) =4
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [56]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두경우에서의 40세와 50세 연봉을 출력

In [57]:
age_30 = 100000
age_60 = 1000000

In [58]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [59]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값
- rand: 균등분포로 난수를 발생
- randn: 정규분포로 난수를 발생
- randint: 균등분포로 정수값을 발생
- suffle: 행렬 데이터를 섞어 줍니다.
- choice: 특정 확률로 데이터를 선택

In [60]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [61]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [62]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [63]:
np.random.randint(10)

1

In [64]:
# shuffle 데이터를 섞어 줌
r = np.random.randint(1, 10, (3,4))
r

array([[8, 9, 3, 9],
       [8, 2, 7, 9],
       [6, 4, 1, 1]])

In [67]:
np.random.shuffle(r)
r

array([[8, 9, 3, 9],
       [6, 4, 1, 1],
       [8, 2, 7, 9]])

In [70]:
# choice
np.random.choice(5, 10, p=[0.1,0,0.4,0.2,0.3])

array([4, 2, 0, 2, 0, 4, 4, 4, 3, 4])

In [74]:
# unique
numbers, counts = np.unique(r, return_counts = True)
print(numbers) # 유니크한 값들
print(counts) # 각 값들이 몇번씩 나왔는지

[1 2 3 4 6 7 8 9]
[2 1 1 1 1 1 2 3]


### 3. 행렬 데이터의 결합
- concatenate

In [80]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(3,2))
na3 = np.random.randint(10, size=(3,3))

In [81]:
# 세로결합
na1

array([[5, 4, 2],
       [9, 7, 1]])

In [82]:
na2

array([[9, 2],
       [1, 0],
       [7, 1]])

In [83]:
na3

array([[8, 9, 0],
       [7, 0, 5],
       [2, 5, 1]])

In [85]:
np.concatenate((na1, na3)) # 세로결합

array([[5, 4, 2],
       [9, 7, 1],
       [8, 9, 0],
       [7, 0, 5],
       [2, 5, 1]])

In [87]:
np.concatenate((na2,na3),axis=1)

array([[9, 2, 8, 9, 0],
       [1, 0, 7, 0, 5],
       [7, 1, 2, 5, 1]])

In [88]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [91]:
# split, var, std, mean ...