### 선형회기 분석
- 프리미어리그 데이터(득점, 실점, 승점)
- 득점, 실점 -> 승점 예측 하는 모델
- scikit-learn 패키지
    - 데이터 마이닝 및 데이터 분석, 모델을 위한 도구
    - 상업적으로 사용이 가능한 오픈소스

In [2]:
import pickle
#선형회귀 모델
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 함수
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

### 분석 절차
- 데이터 로드
- 데이터 전처리
    - 독립 변수와 종속변수를 나눠줌 
    - 학습데이터와 테스트 데이터를 나눠줌
- 데이터 분석 : 선형회귀 모델
- 성능 평가 : MAE
- 예측 코드 작성

In [3]:
# 1. 데이터 로드
p_df = pd.read_csv("datas/premierleague.csv")
p_df.tail(2)

name  gf  ga  points
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [4]:
# 2. 데이터 전처리 : 독립변수, 종속변수 나누기
df_x = p_df[["gf","ga"]]
df_y = p_df[["points"]]
df_y

points
0      100
1       81
2       77
3       75
4       70
5       63
6       54
7       49
8       47
9       44
10      44
11      44
12      42
13      41
14      40
15      37
16      36
17      33
18      33
19      31

In [5]:
# 2. 데이터 전처리 : 학습데이터와 테스트데이터로 나누기
train_x, test_x, train_y, test_y = train_test_split(
    df_x, df_y, test_size=0.3, random_state=1) # test_size: 30센터는 테스트 데이터, 70퍼센트는 train 데이터

In [6]:
len(train_x)

14

In [7]:
# 3. 데이터 분석 : 선형회귀 모델
model = linear_model.LinearRegression() # model이라는 객체 생성

In [8]:
model.fit(train_x, train_y) # 학습된 결과가 모델 객체에 저장되어있다. 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
# 4. 성능평가: MAE
pred_y=model.predict(test_x)
pred_y

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [13]:
test_y["points"].values

array([75, 36, 54, 44, 77, 40])

In [16]:
pred_y = np.around(pred_y.flatten()).astype("int")
pred_y

array([81, 41, 51, 46, 76, 40])

In [20]:
mae = mean_absolute_error(test_y, pred_y)
mae
# 2.83 정도의 오차가 있다.

2.8333333333333335

In [21]:
round(mae, 2)

2.83

In [28]:
# 5. 예측 함수
def make_df(gf, ga):
    return pd.DataFrame({"gf":[gf], "ga":[ga]})

In [36]:
gf, ga = 80, 30
result = int(model.predict(make_df(gf,ga)).flatten()[0])
result

83

In [37]:
p_df.head()

name   gf  ga  points
0    Manchester City  106  27     100
1  Manchester United   68  28      81
2  Tottenham Hotspur   74  36      77
3          Liverpool   84  38      75
4            Chelsea   62  38      70